FLAGS = {
    "Argentina": "🇦🇷",
    "Australia": "🇦🇺",
    "Belgium": "🇧🇪",
    "Bosnia and Herzegovina": "🇧🇦",
    "Brazil": "🇧🇷",
    "Canada": "🇨🇦",
    "Chile": "🇨🇱",
    "China PR": "🇨🇳",
    "Colombia": "🇨🇴",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Czechia": "🇨🇿",
    "Denmark": "🇩🇰",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "England": "🏴",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Haiti": "🇭🇹",
    "Iran": "🇮🇷",
    "Italy": "🇮🇹",
    "Japan": "🇯🇵",
    "Korea Republic": "🇰🇷",
    "Mexico": "🇲🇽",
    "Morocco": "🇲🇦",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Nigeria": "🇳🇬",
    "Norway": "🇳🇴",
    "Paraguay": "🇵🇾",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Saudi Arabia": "🇸🇦",
    "Scotland": "🏴",
    "Senegal": "🇸🇳",
    "South Africa": "🇿🇦",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Türkiye": "🇹🇷",
    "Tunisia": "🇹🇳",
    "USA": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Wales": "🏴",
    "Côte d'Ivoire": "🇨🇮",
    "Algeria": "🇩🇿",
    "Cape Verde": "🇨🇻",
}


def get_flag(team_name):
    return FLAGS.get(team_name, "🏳️")